### ISSUE TITLE
gradlew.bat exited abnormally

### ISSUE THREAD

**Issue by rakeshkhoodeeram** [odrevet/bide_et_musique_flutter#1]
hello,
I am getting this issue when running your project on VS Code.

* Error running Gradle:
ProcessException: Process "C:\...\bide-et-musique-flutter-master\bide-et-musique-flutter-master\android\gradlew.bat" exited abnormally:

  Command: C:\.....\bide-et-musique-flutter-master\bide-et-musique-flutter-master\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.

**Comment by odrevet** [comment]
Hello, 
This is happening because the build script is configured to sign the app, as described in : https://flutter.dev/docs/deployment/android#signing-the-app 

Solutions are : 
* Generate a key with keytool and create an android/key.properties file with a dummy password
* Configure VSCode to build an unsigned apk

I had pushed the edited build.gradle from the manual to avoid doing this modification on each workstation for release. I don't know how other dev manage this with git but I'll be interested to see best practices on this subject
